app:
  jwks: classpath:jwks.json
server:
  port: 8081
spring:
  application:
    name: keycloak-spring-boot-example
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: keycloak-spring-boot-example
            client-authentication-method: private_key_jwt
            authorization-grant-type: authorization_code
            scope:
            - openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8080/realms/test
            user-name-attribute: preferred_username